import { test } from "node:test";
import assert from "node:assert/strict";
import { looksLikePdfUrl, pdfFindingsFromBytes, scanPdfTagTree } from "./index.js";

/**
 * A minimal, hand-built PDF -- one page, one text run, optionally wrapped in a `/Figure` marked-content
 * span with a struct-element tree behind it. Built directly rather than fetched or generated by a
 * PDF-writing library, so every byte in it is accounted for in this file: no binary fixture nobody can
 * read, and no dependency on what a library version happens to emit for "tagged".
 *
 * `tagged` adds `/MarkInfo`, `/StructTreeRoot` and a `Document > Figure` struct element bound to the
 * page's own MCID 0 span (the same linkage a real authoring tool emits, verified against `pdf-lib`'s own
 * reader while writing this test). `lang`/`alt` are independent knobs so each check has a fixture where
 * only the one fact it looks for is missing.
 */
function buildMinimalPdf({ tagged, lang, alt }: { tagged: boolean; lang?: string; alt?: string }): Uint8Array {
  const objs: string[] = [];
  let catalog = "<< /Type /Catalog /Pages 2 0 R";
  if (tagged) catalog += " /StructTreeRoot 6 0 R /MarkInfo << /Marked true >>";
  if (lang) catalog += ` /Lang (${lang})`;
  catalog += " >>";
  objs[1] = catalog;
  objs[2] = "<< /Type /Pages /Kids [3 0 R] /Count 1 >>";
  objs[3] = "<< /Type /Page /Parent 2 0 R /MediaBox [0 0 300 300] /Resources << /Font << /F1 5 0 R >> >> "
    + `/Contents 4 0 R${tagged ? " /StructParents 0" : ""} >>`;
  const content = tagged
    ? "/Figure <</MCID 0>> BDC\nBT /F1 16 Tf 50 150 Td (Hello world) Tj ET\nEMC\n"
    : "BT /F1 16 Tf 50 150 Td (Hello world) Tj ET\n";
  objs[4] = `<< /Length ${content.length} >>\nstream\n${content}endstream`;
  objs[5] = "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>";
  if (tagged) {
    objs[6] = "<< /Type /StructTreeRoot /K [7 0 R] >>";
    objs[7] = "<< /Type /StructElem /S /Document /P 6 0 R /K [8 0 R] >>";
    objs[8] = `<< /Type /StructElem /S /Figure /P 7 0 R /Pg 3 0 R /K 0${alt ? ` /Alt (${alt})` : ""} >>`;
  }
  const n = tagged ? 8 : 5;

  let pdf = "%PDF-1.7\n";
  const offsets: number[] = [0];
  for (let i = 1; i <= n; i++) {
    offsets[i] = Buffer.byteLength(pdf, "latin1");
    pdf += `${i} 0 obj\n${objs[i]}\nendobj\n`;
  }
  const xrefOffset = Buffer.byteLength(pdf, "latin1");
  pdf += `xref\n0 ${n + 1}\n0000000000 65535 f \n`;
  for (let i = 1; i <= n; i++) pdf += `${String(offsets[i]).padStart(10, "0")} 00000 n \n`;
  pdf += `trailer\n<< /Size ${n + 1} /Root 1 0 R >>\nstartxref\n${xrefOffset}\n%%EOF`;
  return new Uint8Array(Buffer.from(pdf, "latin1"));
}

test("looksLikePdfUrl: the extension decides, the query string doesn't hide it", () => {
  assert.equal(looksLikePdfUrl("https://example.com/report.pdf"), true);
  assert.equal(looksLikePdfUrl("https://example.com/report.pdf?download=1"), true);
  assert.equal(looksLikePdfUrl("https://example.com/report.PDF"), true);
  assert.equal(looksLikePdfUrl("https://example.com/report.html"), false);
  assert.equal(looksLikePdfUrl("not a url at all"), false);
});

test("an untagged PDF is one pdf-untagged finding, and nothing else -- no tree to walk", async () => {
  const findings = await pdfFindingsFromBytes(buildMinimalPdf({ tagged: false }));
  assert.deepEqual(findings.map((f) => f.rule), ["pdf-untagged", "pdf-missing-lang"]);
});

test("a tagged PDF with a Figure missing /Alt: tagged so no pdf-untagged, but no /Alt so pdf-figure-no-alt", async () => {
  const findings = await pdfFindingsFromBytes(buildMinimalPdf({ tagged: true, lang: "en-GB" }));
  assert.deepEqual(findings.map((f) => f.rule), ["pdf-figure-no-alt"]);
  assert.equal(findings[0]?.wcag[0], "1.1.1");
  assert.equal(findings[0]?.page, 1, "the Figure's /Pg resolves to page 1");
});

test("a tagged PDF whose Figure HAS /Alt: no finding at all -- the positive control for pdf-figure-no-alt", async () => {
  const findings = await pdfFindingsFromBytes(
    buildMinimalPdf({ tagged: true, lang: "en-GB", alt: "A decorative flourish" }));
  assert.deepEqual(findings, []);
});

test("tagged, alt present, but no /Lang: only pdf-missing-lang", async () => {
  const findings = await pdfFindingsFromBytes(buildMinimalPdf({ tagged: true, alt: "A decorative flourish" }));
  assert.deepEqual(findings.map((f) => f.rule), ["pdf-missing-lang"]);
  assert.equal(findings[0]?.wcag[0], "3.1.1");
});

test("every finding names the pdf-tag-tree layer, so a report can label it", async () => {
  const findings = await pdfFindingsFromBytes(buildMinimalPdf({ tagged: false }));
  assert.ok(findings.length > 0);
  for (const finding of findings) assert.equal(finding.source, "pdf-tag-tree");
});

/** Swaps `global.fetch` for the duration of one test, restored even if the test throws. */
async function withFetch(stub: typeof fetch, run: () => Promise<void>): Promise<void> {
  const real = globalThis.fetch;
  globalThis.fetch = stub;
  try {
    await run();
  } finally {
    globalThis.fetch = real;
  }
}

test("scanPdfTagTree: a fetched PDF is read exactly like one already in hand", async () => {
  const bytes = buildMinimalPdf({ tagged: false });
  await withFetch(
    (async () => new Response(bytes as BodyInit, { status: 200 })) as typeof fetch,
    async () => {
      const result = await scanPdfTagTree("https://example.com/report.pdf");
      assert.equal(result.ok, true);
      assert.deepEqual(result.ok && result.findings.map((f) => f.rule), ["pdf-untagged", "pdf-missing-lang"]);
    },
  );
});

test("scanPdfTagTree: a non-2xx response is 'not run', not a thrown error", async () => {
  await withFetch(
    (async () => new Response("nope", { status: 404 })) as typeof fetch,
    async () => {
      const result = await scanPdfTagTree("https://example.com/missing.pdf");
      assert.equal(result.ok, false);
      assert.match(result.ok ? "" : result.error, /404/);
    },
  );
});

test("scanPdfTagTree: a network failure is 'not run', not a thrown error", async () => {
  await withFetch(
    (async () => { throw new Error("ECONNREFUSED"); }) as typeof fetch,
    async () => {
      const result = await scanPdfTagTree("https://example.com/report.pdf");
      assert.equal(result.ok, false);
      assert.match(result.ok ? "" : result.error, /ECONNREFUSED/);
    },
  );
});

test("scanPdfTagTree: bytes that are not a PDF at all are 'not run', not a thrown error", async () => {
  await withFetch(
    (async () => new Response("<html>not a pdf</html>", { status: 200 })) as typeof fetch,
    async () => {
      const result = await scanPdfTagTree("https://example.com/report.pdf");
      assert.equal(result.ok, false);
    },
  );
});
